---
apiVersion: v1
kind: pod
metadata: hello-pod
  name: hello-pod
  labels: 
    app: hello-pod
spec:
  containers:
    - name: web
      image: httpd
      ports:
        - name: web
          containerport: 80
          protocol: TCP
              